apiVersion: v1
kind: Service
metadata:
  name: app-ui-svc
  namespace: prod
spec:
  selector:
    app: app-ui
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30683
  type: NodePort
